import 'app/globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'

import Footer from 'app/components/footer'
import { Navbar } from 'app/components/navbar'

const LXGWWenKaiScreenFont = localFont({
  src: '../public/fonts/LXGWWenKaiScreen.ttf',
  display: 'swap',
  variable: '--font-lxgwwenkaiscreen',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cn = (...classes: string[]) => classes.filter(Boolean).join(' ')

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'text-black bg-white dark:text-white dark:bg-black font-sans',
        LXGWWenKaiScreenFont.variable,
      )}
    >
      <body className="antialiased max-w-xl px-4 sm:px-0 mt-8 mx-auto">
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
