import type { Metadata } from 'next'
import localFont from 'next/font/local'
import 'app/globals.css'

const LXGWWenKaiScreenFont = localFont({
  src: '../public/fonts/LXGWWenKaiScreen.ttf',
  display: 'swap',
  variable: '--font-lxgwwenkaiscreen',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cn = (...classes: string[]) => classes.filter(Boolean).join(' ')

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'text-black bg-white dark:text-white dark:bg-black font-sans',
        LXGWWenKaiScreenFont.variable,
      )}
    >
      <body className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          {children}
        </main>
      </body>
    </html>
  )
}
